
service: macos-http
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  MacosHelloFn:
    handler: hello.handler
    events:
       - httpApi:
          path: /hello
          method: Get

  MacOsByeFn:
    handler: bye.handler
    events:
       - httpApi:
          path: /bye
          method: Get



